source <sfile>:p:h/ale.vim
source <sfile>:p:h/indentLine.vim
source <sfile>:p:h/jedi-vim.vim
source <sfile>:p:h/nvim-miniyank.vim
source <sfile>:p:h/tmuxline.vim
source <sfile>:p:h/vim-airline.vim
source <sfile>:p:h/vim-closetag.vim
source <sfile>:p:h/vimtex.vim
source <sfile>:p:h/vim-better-whitespace.vim
